# Generated by Django 3.0 on 2022-03-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20220313_2147'),
        ('posts', '0002_auto_20220314_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message_html',
        ),
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(default='', max_length=100, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='post',
            name='start',
            field=models.CharField(default='', max_length=100, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='post',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='circle.Circle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(default='', max_length=50, verbose_name='Message'),
        ),
    ]
