# Generated by Django 3.0 on 2022-03-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220311_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helper',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_code',
        ),
    ]
