# Generated by Django 3.0 on 2022-03-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circlemember',
            old_name='user',
            new_name='member',
        ),
        migrations.AddField(
            model_name='circle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circle_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='circlemember',
            unique_together={('circle', 'member')},
        ),
    ]
