# Generated by Django 3.0 on 2022-03-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20220313_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['name', 'owner']},
        ),
    ]
